### ISSUE TITLE
Usar um único arduino

### ISSUE THREAD

**Issue by joary** [lasseufpa/Miritronica#2]
__Input:__

Atualmente o robô utiliza dois arduinos para controlar os servos e a voz

__Output:__

Fazer um único software para controlar ambos

**Comment by igorsantosp** [comment]
Protótipo deste código já commitado no branch "single arduino", faltando testar direto no wall-ti e otimizá-lo de acordo com a resposta dos servos e do speaker do robô.

**Comment by CaioMM** [comment]
Uma placa foi produzida para o robô de modo que os 2 arduinos foram substituídos
